name = "DocTest3"
version = "0.1.0"
defaultTargets = ["doctest3"]

[[require]]
name = "doc-gen4"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"

[[lean_lib]]
name = "DocTest3"

[[lean_exe]]
name = "doctest3"
root = "Main"
